#!/bin/sh

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
sketchybar --bar position=top height=30 blur_radius=30 color=0x00ffffff

##### Defaults #####
default=(
  padding_left=3
  padding_right=3
  icon.font="JetBrainsMono Nerd Font:Bold:13.0"
  label.font="JetBrainsMono Nerd Font:Bold:13.0"
  icon.color=0xffcad3f5
  label.color=0xffcad3f5
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Left Items #####
# Adding Mission Control Space Indicators

# SPACE_ICONS=("🏠" "💬" "💻" "🧪" "🌐" "☸️")
# SPACE_NAMES=("home" "comms" "code" "test" "browse" "k8s")

sketchybar --add event aerospace_workspace_change

sketchybar --add item space left \
          --subscribe space aerospace_workspace_change \
          --set space \
              script="$PLUGIN_DIR/aerospace.sh" \
              background.color=0xff1e1e2e \
              background.corner_radius=5 \
              background.border_width=1 \
              background.border_color=0xff89b4fa \
              background.height=25 \
              background.padding_right=7 \
              background.drawing=on \
              label.padding_left=7 \
              label.padding_right=7

# for sid in $(aerospace list-workspaces --all); do
#     sketchybar --add item space.$sid left \
#         --subscribe space.$sid aerospace_workspace_change \
#         --set space.$sid \
#         background.color=0x44ffffff \
#         background.corner_radius=5 \
#         background.height=20 \
#         background.drawing=off \
#         label="$sid" \
#         click_script="aerospace workspace $sid" \
#         script="$CONFIG_DIR/plugins/aerospace.sh $sid"
# done
#
# for i in "${!SPACE_ICONS[@]}"
# do
#   sid="$(($i+1))"
#   space=(
#     space="$sid"
#     icon="${SPACE_ICONS[i]} ${SPACE_NAMES[i]}"
#     icon.color=0xffcdd6f4
#     icon.padding_left=7
#     icon.padding_right=7
#     label.padding_left=7
#     label.padding_right=7
#     background.color=0x3389b4f9
#     background.corner_radius=5
#     background.border_color=0xff89b4fa
#     background.border_width=1
#     background.height=25
#     background.padding_right=3
#     background.padding_left=3
#     label.drawing=off
#     script="$PLUGIN_DIR/space.sh"
#     click_script="yabai -m space --focus $sid"
#   )
#   sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
# done

sketchybar --add bracket spaces '/space\..*/' \
           --set spaces background.color=0xff1e1e2e \
                        background.corner_radius=5 \
                        background.border_width=1 \
                        background.border_color=0xff89b4fa \
                        background.height=25

sketchybar --add item chevron left \
           --set chevron icon= label.drawing=off

sketchybar --add item front_app left \
           --subscribe front_app front_app_switched \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
                           background.color=0xff1e1e2e \
                           background.corner_radius=5 \
                           background.border_width=1 \
                           background.border_color=0xff89b4fa \
                           background.height=25 \
                           background.padding_left=7 \
                           background.padding_right=7 \
                           label.padding_left=7 \
                           label.padding_right=7

##### Right Items #####
sketchybar --add item calendar right \
           --set calendar update_freq=10 icon=􀉉 script="$PLUGIN_DIR/calendar.sh" \
                          background.color=0xff1e1e2e \
                          background.corner_radius=5 \
                          background.border_width=1 \
                          background.border_color=0xfff38ba8 \
                          background.height=25 \
                          background.padding_left=7 \
                          background.padding_right=7 \
                          label.padding_left=7 \
                          label.padding_right=7

sketchybar --add item clock right \
           --set clock update_freq=10 icon=  script="$PLUGIN_DIR/clock.sh" \
                       background.color=0xff1e1e2e \
                       background.corner_radius=5 \
                       background.border_width=1 \
                       background.border_color=0xffa6e3a1 \
                       background.height=25 \
                       background.padding_left=7 \
                       background.padding_right=7 \
                       label.padding_left=7 \
                       label.padding_right=7

sketchybar --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
                         background.color=0xff1e1e2e \
                         background.corner_radius=5 \
                         background.border_width=1 \
                         background.border_color=0xfff2cdcd \
                         background.height=25 \
                         background.padding_left=7 \
                         background.padding_right=7 \
                         label.padding_left=7 \
                         label.padding_right=7 \
           --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
