after-startup-command = ['exec-and-forget sketchybar']

exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

# Start AeroSpace at login
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
default-root-container-orientation = 'horizontal'

# on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

automatically-unhide-macos-hidden-apps = false

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 12
inner.vertical = 12
outer.left = 12
outer.bottom = 12
outer.top = [{ monitor.'LG ULTRAGEAR' = 38 }, { monitor.'built-in' = 35 }, 10]
outer.right = 12

[mode.main.binding]
# terminal shortcuts
cmd-enter = '''exec-and-forget open -na /Applications/Ghostty.app'''
alt-t = '''exec-and-forget open -na /Applications/kitty.app'''

# layout switch
alt-minus = 'layout tiles horizontal vertical'
alt-backslash = 'layout accordion horizontal vertical'

# join between windows
alt-ctrl-h = 'join-with left'
alt-ctrl-j = 'join-with down'
alt-ctrl-k = 'join-with up'
alt-ctrl-l = 'join-with right'

# switch focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# swap windows
cmd-shift-h = 'swap left --wrap-around'
cmd-shift-j = 'swap down --wrap-around'
cmd-shift-k = 'swap up --wrap-around'
cmd-shift-l = 'swap right --wrap-around'

# resize windows
alt-shift-j = 'resize smart -60'
alt-shift-k = 'resize smart +60'

# switch workspaces
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'

# move windows to workspaces
alt-ctrl-1 = 'move-node-to-workspace 1'
alt-ctrl-2 = 'move-node-to-workspace 2'
alt-ctrl-3 = 'move-node-to-workspace 3'
alt-ctrl-4 = 'move-node-to-workspace 4'
alt-ctrl-5 = 'move-node-to-workspace 5'
alt-ctrl-6 = 'move-node-to-workspace 6'
alt-ctrl-7 = 'move-node-to-workspace 7'

# alt-tab behavior
alt-tab = 'workspace-back-and-forth'

# move all windows to monitor (if connected to external monitor)
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']


[workspace-to-monitor-force-assignment]
1 = 'secondary'
2 = 'secondary'
3 = 'secondary'
7 = 3

[[on-window-detected]]
if.app-id = 'com.logi.cp-dev-mgr'
if.app-name-regex-substring = 'logi'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.if.Amphetamine'
if.app-name-regex-substring = 'amphetamine'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
if.app-name-regex-substring = 'whatsapp'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'net.freemacsoft.AppCleaner'
if.app-name-regex-substring = 'AppCleaner'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.apple.finder'
if.app-name-regex-substring = 'finder'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'com.bitgapp.eqmac'
if.app-name-regex-substring = 'eqMac'
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'org.pqrs.Karabiner-Elements.Settings'
run = ['layout floating']
