#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh"  # Loads all defined icons

FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants
PADDINGS=3
ITEM_PADDINGS=4

##### Bar Appearance #####
bar=(
  shadow=off
  position=top
  sticky=on
  y_offset=0
  height=30
  margin=0
  topmost=window
  # blur_radius=1
  color=0x66000000
)

sketchybar --bar "${bar[@]}"

##### Defaults #####
default=(
  updates=when_shown
  padding_left=$PADDINGS
  padding_right=$PADDINGS
  icon.font="$FONT:Bold:13.0"
  label.font="$FONT:Semibold:13.0"
  icon.color=0xffcad3f5
  label.color=0xffcad3f5
  icon.padding_left=$ITEM_PADDINGS
  icon.padding_right=$ITEM_PADDINGS
  label.padding_left=$ITEM_PADDINGS
  label.padding_right=$ITEM_PADDINGS
)
sketchybar --default "${default[@]}"

##### Left Items #####
source "$ITEM_DIR/left/aerospace.sh"
source "$ITEM_DIR/left/front_app.sh"

##### Right Items #####
source "$ITEM_DIR/right/calendar.sh"
source "$ITEM_DIR/right/clock.sh"
source "$ITEM_DIR/right/battery.sh"
source "$ITEM_DIR/right/cpu.sh"
source "$ITEM_DIR/right/ram.sh"
source "$ITEM_DIR/right/brew.sh"
# source "$ITEM_DIR/right/wifi.sh"

sketchybar --hotload true

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
