#!/usr/bin/env bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/colors.sh" # Loads all defined colors
source "$CONFIG_DIR/icons.sh"  # Loads all defined icons

FONT="SF Pro"
PADDINGS=3
ITEM_PADDINGS=4

##### Bar Appearance #####
bar=(
  shadow=off
  position=top
  sticky=on
  height=30
  margin=0
  topmost=window
  # blur_radius=1
  color=0x66000000
)

sketchybar --bar "${bar[@]}"

##### Defaults #####
default=(
  updates=when_shown
  padding_left=$PADDINGS
  padding_right=$PADDINGS
  icon.font="$FONT:Bold:13.0"
  label.font="$FONT:Semibold:13.0"
  icon.color=0xffcad3f5
  label.color=0xffcad3f5
  icon.padding_left=$ITEM_PADDINGS
  icon.padding_right=$ITEM_PADDINGS
  label.padding_left=$ITEM_PADDINGS
  label.padding_right=$ITEM_PADDINGS
)
sketchybar --default "${default[@]}"

##### Left Items #####
source "$ITEM_DIR/aerospace.sh"
# source "$ITEM_DIR/yabai.sh"
source "$ITEM_DIR/front_app.sh"

##### Center Items #####
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/clock.sh"

##### Right Items #####
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/sound.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/brew_outdated.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/ram_percent.sh"

sketchybar --hotload true

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
